import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SidePanelComponent from "@/components/SidePanel/SidePanelComponent";

const poppins = Poppins({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`ml-20 ${poppins.className}`}>
        <Navbar />
        <div className="flex space-x-4 py-10">
          <div className="w-[65%] flex items-center justify-center">
            {children}
          </div>
          <div className="w-[35%]">
            <SidePanelComponent />
          </div>
        </div>
      </body>
    </html>
  );
}
